version: '3'

services:
  MongoDB1:
    restart: always
    container_name: mongo1
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password
    volumes:
      - /data/mongodb:/mongodb

  MongoDB2:
    restart: always
    container_name: mongo2
    image: bitnami/mongodb:latest
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password
    volumes:
      - /data/mongodb2:/mongodb
