version: '3'

services:
  MongoDB1:
    restart: always
    container_name: mongo1
    image: bitnami/mongodb:latest
    ports:
      - "27019:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_EXTRA_FLAGS=--profile=1 --slowms=1
    volumes:
      - /data/mongodb:/mongodb

  MongoDB2:
    restart: always
    container_name: mongo2
    image: bitnami/mongodb:latest
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password
      - MONGODB_EXTRA_FLAGS=--profile=1 --slowms=1
    volumes:
      - /data/mongodb2:/mongodb
